# Generated by Django 5.1.7 on 2025-03-20 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="이름")),
                ("age", models.IntegerField(verbose_name="나이")),
                (
                    "location",
                    models.CharField(max_length=100, verbose_name="현재 위치"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("normal", "정상"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        default="normal",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("heart_rate", models.IntegerField(verbose_name="심박수")),
                (
                    "activity_status",
                    models.CharField(max_length=100, verbose_name="활동 상태"),
                ),
                ("temperature", models.FloatField(verbose_name="체온")),
                ("humidity", models.IntegerField(verbose_name="주변 습도")),
            ],
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="알림 제목")),
                ("details", models.TextField(verbose_name="알림 세부 내용")),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("info", "정보"),
                            ("warning", "주의"),
                            ("danger", "위험"),
                        ],
                        default="info",
                        max_length=20,
                        verbose_name="알림 유형",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="알림 시간"),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="monitoring.person",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
